#php_version: php-5.6.22-1
php_version: php-7.1.5-1
php6_version: php-5.6.30-1
#php_version: php-5.4.45-1
php_package_url: "{{ package_url_prefix }}/php/{{ php_version }}.centos7.{{ ansible_architecture }}.rpm"
php6_package_url: "{{ package_url_prefix }}/php/{{ php6_version }}.centos6.{{ ansible_architecture }}.rpm"
php_user: www
php_install_dir: /usr/local/webserver/php7.1.5
php_logs_dir: /data0/logs/php-fpm
