---
 - name: copy the php template
   template:
    src: template.j2
    dest: "{{ php_conf_dir }}/{{ nginx_server_name }}.conf"
   when: type == "php"
 
# - name: change the domain name in the php conf
#   replace:
#    dest: "{{ php_conf_dir }}/{{ nginx_server_name }}.conf"
#    regexp: 'template'
#    replace: '{{ nginx_server_name }}'

 - name: start php program
   shell: "{{ php_bin_dir }}/php-fpm > /dev/null 2>&1"
   register: result
   ignore_errors: True

 - name: restart php program
   shell: "kill -USR2 `ps aux|grep php|grep master|grep -v grep|awk '{print $2}'`"
   when: result.rc != 0
