[hekad]
maxprocs = 2

[nginx_access_logs]
type = "LogstreamerInput"
splitter = "TokenSplitter"
decoder = "nginx_access_decoder"
log_directory = "/data0/logs/nginx"
file_match = '.*\.access\.log\-?(?P<Index>\d+)?(.gz)?'
#file_match = '.*\.access\.log'
priority = ["^Index"]

[nginx_access_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

[nginx_access_decoder.config]
tz = "Asia/Shanghai"
user_agent_transform = true
log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$host" "$request_time" "$request_length" "$upstream_addrs" "$upstream_response_time" "$upstream_status"'
type = "nginx.access"

#[GeoIpDecoder]
#db_file="/var/cache/hekad/GeoLiteCity.dat"
#source_ip_field="remote_addr"
#target_field="geoip"

[ESJsonEncoder]
es_index_from_timestamp = true
type_name = "%{Type}"

#[LogstreamerInput]
#log_directory = "/data0/logs/nginx"
#file_match = '.*\.access\.log'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "ESJsonEncoder"
