---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Heka
   yum: 
    name: "{{ heka_rpm }}"
    state: present

 - block:
    - debug:
       mes: "Generate Configuration"
    - file:
       path: "{{ confdir }}"
       state: directory
    - template:
       dest: "/etc/systemd/system/{{ item }}"
       src: "{{ item }}.j2"
      with_items:
       - "heka.service"
    - template:
       dest: "{{ confdir }}/{{ item }}"
       src: "{{ item }}.j2"
      with_items:
       - "kafka.toml"
      notify:
       - Restart Heka

 - name: Setup Auto Start When System Boot
   command: "systemctl enable Heka"
...
