---
 - hosts: all
  
   tasks:

   - name: Chmod /etc/rc.d/rc.local
     file:
       path: '/etc/rc.d/rc.local'
       mode: "u+rwx"
       state: file

# - name: Set System Command's Subcommand Automatic Completion
# #   shell: "source /usr/share/bash-completion/bash_completion"
#
   - block:
     - debug:
        msg: "Change PYPI Source"
     - file:
        path: "~/.pip"
        state: directory

   - name: Update Pip
     pip:
      name: "pip"
      state: latest

   - name: Update Kernel
     yum:
      name: "*"
      state: latest

   - name: Reboot System
     command: init 6
     ignore_errors: True
...
