---
 - hosts: centos
   roles:
    - role: set_sysctl
    - role: install_base_soft
    - role: set_sshd
    - role: add_users
    - role: set_limits
    - role: set_others
    - role: set_nameserver

 - hosts: ubuntu
   become: yes
   roles:
    - role: set_sysctl
    - role: install_base_soft
    - role: set_sshd
    - role: add_users
    - role: set_limits
    - role: set_others
    - role: set_nameserver
...
