---
- name: Create mongodb Directory.
  file: 
    path: "{{ item }}"
    state: directory 
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
  with_items:
   - "{{ mongodb_datapath }}"
   - "{{ mongodb_dir_path }}/logs"

- name: Ensure mongodb is configured.
  template:
    src: "{{item.filename}}.j2"
    dest: "{{ mongodb_dir_path }}/{{ item.filename }}"
    mode: "{{ item.mode }}"
  with_items:
    - { 'filename': 'mongod.conf', 'mode': '0644' }
    - { 'filename': 'mongod', 'mode': '0700' }

- name: Add Auto Start
  lineinfile:
    path: /etc/rc.d/rc.local
    line: "{{ mongodb_dir_path }}/mongod start"

#- block:
#  - name: copy repset js to agent.
#    template: src=repset.js.j2 dest=/tmp/ansible_mongodb_repset.js

#  - name: Config repset.
#    shell: "/usr/local/mongodb/bin/mongo --port {{ mongodb_port }} admin < /tmp/ansible_mongodb_repset.js"
#  when: mongodb_replSet and mongodb_replSet_exec
#  run_once: true
