---
name: "mysql"
version: "-5.6.29-1"
package_name: "{{ name }}{{ version }}.centos{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
mysql_package_url: "{{ package_url_prefix }}/mysql/{{ package_name }}"
mysql_user: mysql
mysql_port: 3306
mysql_install_dir: /usr/local/webserver/mysql
mysql_datadir: /data0/mysql
