---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Download Logstash Package
   uri:
    url: "{{ package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ package_fullname }}"

 - name: Install Logstash
   yum: 
    name: "{{ tempdir }}/{{ package_fullname }}"
    state: present

 - block:
    - debug:
       msg: "Configuration"
    - file:
       path: "{{ confdir }}/{{ item }}"
       state: directory
      with_items:
       - "patterns"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ confdir }}/{{ item }}"
      with_items:
       - "conf.d/redis.conf"
    - synchronize:
       src: "./"
       dest: "{{ confdir }}"

 - name: "Setup Logstash Auto Start"
   service:
    name: "logstash" 
    state: "restarted"    
    enabled: yes
...
