---
 - name: Copy Docker.repo
   copy: 
    src: docker.repo 
    dest: /etc/yum.repos.d/docker.repo

 - name: Yum Install Docker-engine 
   yum: 
    name: docker-engine 
    state: present 
    update_cache: yes

 - block:
    - debug:
       msg: Add SSL Certificate
    - copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest}}"
      with_items:
       - {src: cacert.pem, dest: /etc/pki/ca-trust/source/anchors/}
       - {src: nginx.crt, dest: /etc/pki/ca-trust/source/anchors/}
    - shell: update-ca-trust extract
    - shell: cat /etc/pki/ca-trust/source/anchors/cacert.pem >> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem 
      notify: 
       - Restart Docker-engine

...
