---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Git Clone The Code
   git:
     repo: "{{ git_url }}/{{ git_url_suffix}}"
     dest: "{{ web_dir }}/{{ nginx_server_name }}"
     version: "{{ git_branch }}"
     accept_hostkey: yes
     clone: yes
 
 - name: Change Owner Of The Code
   file:
     path: "{{ web_dir}}/{{ nginx_server_name }}"
     owner: www
     group: www
     state: directory
     recurse: yes
