---
# 配置 RocketMQ Master 和 Slave 节点

- name: Configure Master Broker A
  template:
    src: broker-a.properties.j2
    dest: /opt/rocketmq/conf/broker.conf
  when: inventory_hostname in groups['master-a']

- name: Configure Slave Broker A
  template:
    src: broker-a-s.properties.j2
    dest: /opt/rocketmq/conf/broker.conf
  when: inventory_hostname in groups['slave-a']

- name: Configure Master Broker B
  template:
    src: broker-b.properties.j2
    dest: /opt/rocketmq/conf/broker.conf
  when: inventory_hostname in groups['master-b']

- name: Configure Slave Broker B
  template:
    src: broker-b-s.properties.j2
    dest: /opt/rocketmq/conf/broker.conf
  when: inventory_hostname in groups['slave-b']


- name: Set RocketMQ systemd service
  template:
    src: rocketmq-broker.service.j2
    dest: /etc/systemd/system/rocketmq-broker.service

- name: set RocketMQ Nameserver systemd service
  template:
    src: rocketmq-nameserver.service.j2
    dest: /etc/systemd/system/rocketmq-nameserver.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: start rocketmq-nameserver and rocketmq-broker
  systemd_service:
    name: "{{ item }}"
    state: started
  with_items:
    - "rocketmq-broker"
    - "rocketmq-nameserver"