---
# 安装所需的软件并下载 RocketMQ

- name: Ensure Java is installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - java-21-openjdk  # 在 CentOS/Rocky Linux 上的包名
    - openjdk-21-jdk  # 在 Ubuntu/Debian 上的包名

- name: Download RocketMQ tarball
  get_url:
    url: {{ download_url }}
    dest: /tmp/rocketmq.tar.gz

- name: Extract RocketMQ tarball
  unarchive:
    src: /tmp/rocketmq.tar.gz
    dest: /opt/rocketmq
    remote_src: yes
