---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"
# - name: Delete Mysql User From Table
#   mysql_user:
#    login_user: "root"
#    login_unix_socket: "/data0/mysql/3306/mysql.sock"
#    name: "{{ item }}"
    #host_all: yes
#    state: absent
#   with_items:
#    - "{{ users }}"
 - name: Delete Mysql User From Table
   command: /usr/local/webserver/mysql/bin/mysql --socket=/data0/mysql/3306/mysql.sock -e "drop user {{ item }}@'%'"
   with_items:
    - "{{ users }}"
