---
 - name: Modify /etc/NetworkManager/NetworkManager.conf
   copy: 
    src: NetworkManager.conf 
    dest: /etc/NetworkManager/NetworkManager.conf
   when: ansible_distribution_major_version == '7'
   notify:
    - Restart NetworkManager
 - meta: "clear_host_errors"

 - name: Add Nameserver
   template: 
    src: resolv.conf.j2 
    dest: /etc/resolv.conf
...
