---
 - hosts: lnmp
   roles:
    - nginx
    - php
    - mysql

 - hosts: nginx
   roles:
    - nginx

 - hosts: php
   roles:
    - php

 - hosts: mysql
   roles:
    - mysql

 - hosts: percona_tools
   roles:
    - percona_tools
...
