---
 - hosts: lnmp
   become: yes
   become_method: "{{ become_method }}"
   roles:
    - nginx
    - php
    - phpredis
    - mcrypt

 - hosts: nginx
   become: yes
   roles:
    - nginx

 - hosts: php
   become: yes
   roles:
    - php
    - phpredis
    - mcrypt


 - hosts: mysql
   become: yes
   roles:
     - mysql
...
