---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Download Kibana Package
   uri:
    url: "{{ package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ fullname }}"
    validate_certs: yes

 - name: Install X-pack
   shell: "{{ basedir }}/bin/elasticsearch-plugin install x-pack"

 - block:
    - debug:
       msg: "Install Kibana"
    - unarchive:
       src: "{{ tempdir }}/{{ fullname }}" 
       dest: "{{ tempdir }}"
       copy: no
       creates: "{{ tempdir }}/{{ name }}-{{ version }}"
    - synchronize:
       src: "{{ tempdir }}/{{ name }}-{{ version }}/"
       dest: "{{ basedir }}"
      delegate_to: "{{ inventory_hostname }}"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ basedir }}/{{ item }}"
      with_items:
       - "config/kibana.yml"

 - name: Configure Kibana Nginx Reverse Proxy
   template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_basedir }}/conf/vhosts/{{ item }}"
   with_items:
    - "kibana.miguan.com.conf"
   notify:
    - Reload Nginx

 - block:
    - debug:
       msg: "Setup Kibana Auto Start"
    - template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
       - "kibana.service"
    - service:
       name: "kibana"
       state: "restarted"
       enabled: yes
...
