---
node_version: "v8.9.4"
node_package_url: "https://npm.taobao.org/mirrors/node/{{ node_version }}/node-{{ node_version }}-linux-x64"
node_install_dir: "/usr/local/webserver"
node_link_dir: "/usr/local/webserver/node"
