---
 - name: Import Secret Yml
   include_vars: "{{ item }}"
   with_items:
     - "secret.yml"

 - name: Get Composer  
   get_url:
     url: "{{ composer_url }}"
     dest: "{{ build_dir }}"

 - name: Move Composer To Path
   synchronize:
     src: "{{ build_dir }}/{{ composer_name }}"
     dest: /usr/bin/
   delegate_to: "{{ inventory_hostname }}"

 - name: Move Composer To Path
   shell: "mv  {{ composer_name }}  composer"
   args:
     chdir: /usr/bin

 - name: Change Mode
   file:
     path: /usr/bin/composer
     mode: u+x

 - setup: filter="ansible_env"
 - name: Add Composer Mirror Source
   shell: "/usr/bin/composer config -g repo.packagist composer https://packagist.phpcomposer.com"
   environment:
     PATH: "/usr/local/webserver/php/bin:{{ ansible_env.PATH }}"
...
