---
 - name: Check The Main Domain Nginx Conf Exist
   stat:
     path: "{{ nginx_conf_dir }}/{{ main_domain }}.conf"
   register: nginx_conf_result

 - name: Template The Nginx Conf If Not Exist
   template:
     src: server.conf.j2
     dest: "{{ nginx_conf_dir }}/{{ main_domain }}.conf"
   when: not nginx_conf_result.stat.exists 

 - name: Update Nginx Conf
   blockinfile:
     path: "{{ nginx_conf_dir }}/{{ main_domain }}.conf"
     marker: "# {mark} ANSIBLE MANAGED BLOCK {{ pre_domain }}"
     block: |
       server {
                   listen 80;
                   server_name {{ nginx_server_name }};
                   index index.html index.htm;
                   root {{ sub_domain_dir }};

                   access_log off;
            }
     state: present
   when: nginx_conf_result.stat.exists
   notify:
     - Reload Nginx
