---
 - name: Install Base Software
   yum: 
    name: "{{ item }}" 
    state: present
   with_items:
    - screen 
    - git

 - name: Git Clone Murder
   git:
     repo: https://github.com/lg/murder.git
     dest: /usr/local/murder
     clone: yes 

 - name: Set tracker as system service on centos6
   template: 
     src: "{{ item.src }}.j2"
     dest: "/etc/init.d/{{ item.dest }}"
   with_items:
     - { src: 'tracker', dest: 'murder-tracker' }
     - { src: 'seeder', dest: 'murder-seeder' }
   when: ansible_distribution_major_version == '6'

 - name: chmod the persimision for murder-tracker on centos6
   file:
     path: "/etc/init.d/{{ item }}"
     mode: 0755
   with_items:
     - murder-tracker
     - murder-seeder
   when: ansible_distribution_major_version == '6'

 - name: Create the seeder.conf
   template: 
     src: seeder.conf.j2
     dest: /usr/local/murder/dist/seeder.conf

 - name: Set tracker as system service on centos7
   template:
     src: "{{ item.src }}.centos7.j2"
     dest: "/etc/systemd/system/{{ item.dest.service }}"
   with_items:
     - { src: 'tracker', dest: 'murder-tracker' }
     - { src: 'seeder', dest: 'murder-seeder' } 
   when: ansible_distribution_major_version == '7'
...
