---
 - name: Install PHP on centos7
   yum:
    name: "{{ php_package_url }}"
    state: present
   when: ansible_distribution_major_version == '7'

 - name: Install PHP Require Packages
   yum:
     name: ["libxslt", "libX11", "libXpm", "libpng", "libjpeg", "libicu"]
     state: present
   when: ansible_distribution_major_version == '7'

 - name: Generate Logs Directory
   file:
    path: "{{ php_logs_dir }}"
    owner: "{{ php_user }}"
    group: "{{ php_user }}"
    recurse: yes
    state: directory

 - name: Create directory var/run/
   file:
     path: "{{ php_install_dir}}/var/run"
     recurse: yes
     state: directory

 - name: Set php.ini and php-fpm.conf to php config dir
   template:
     src: "{{ item }}"
     dest: "{{ php_install_dir }}/etc/"
   with_items:
     - "php.ini"
     - "php-fpm.conf"


 - name: Start Daemon When System Boot
   lineinfile:
    dest: /etc/rc.local
    line: "{{ php_install_dir }}/sbin/php-fpm"     

 - name: Set Environment PATH
   lineinfile: 
    dest: /etc/profile    
    line: "export PATH={{ php_install_dir }}/bin:$PATH"

...
