---
 - name: Copy mysql.repo to /etc/yum.repos.d
   copy:
     src: mysql.repo
     dest: /etc/yum.repos.d
   when: "ansible_distribution == 'CentOS'"

 - name: Install Mysql
   yum:
    name: "mysql-server"
    state: latest
   when: "ansible_distribution == 'CentOS'"

 - name: Copy my.cnf
   copy:
     src: my.cnf
     dest: /etc/
   when: "ansible_distribution == 'CentOS'"

...
