---

 - name: Close Firewall On Centos 7
   service: 
    name: firewalld
    state: stopped
    enabled: no
   when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'"
   ignore_errors: True

 - name: Chmod /etc/rc.d/rc.local
   file: 
    path: '/etc/rc.d/rc.local'
    mode: "u+rwx"
    state: file
   when: "ansible_distribution == 'CentOS'"


 - name: Create directory /data/logs
   file:
    path: "{{ item }}"
    state: directory
    owner: "ops"
    group: "ops"
    mode: 0755
   with_items:
     - "/data/logs/engine"
     - "/data/logs/wallet"
     - "/data/logs/user"
     - "/data/logs/robot"
     - "/data/logs/gateway"
     - "/data/logs/admin"

 - name: Create directory /data/logs/nginx
   file:
    path: "{{ item }}"
    state: directory
    owner: "www"
    group: "www"
    mode: 0755
   with_items:
     - "/data/logs/nginx"
     - "/data/logs/php"


 - name: Run restore context to reload selinux on Centos
   shell: restorecon -R /etc
   when: "ansible_distribution == 'CentOS'"

 - name: Change nproc from 4096 to 65535
   replace:
     path: /etc/security/limits.d/20-nproc.conf
     regexp: '4096'
     replace: '65535'
   when: "ansible_distribution == 'CentOS'"

 - name: Stop and disable service postfix
   service:
     name: postfix
     state: stopped
     enabled: false
   when: "ansible_distribution == 'CentOS'"

 - name: Start and enable supervisord
   service:
     name: supervisord
     state: started
     enabled: true
   when: "ansible_distribution == 'CentOS'"





...