---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Add Es Groups
   group:
    name: "{{ item.user }}"
    gid: "{{ item.id }}"
    state: present
    system: yes
   with_items: "{{ users }}"

 - name: Add Es Users
   user:
    name: "{{ item.user }}"
    group: "{{ item.user }}"
    uid: "{{ item.id }}"
    createhome: no
    comment: "{{ item.comment }}"
    shell: /sbin/nologin
    state: present
    system: yes
   with_items: "{{ users }}"

 - name: Sysctl vm.max_map_count
   sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
   with_items:
    - {name: vm.max_map_count, value: 262144}

 - name: Unlimit Mlockall
   pam_limits:
    domain: "*"
    limit_item: "{{ item.item }}"
    limit_type: "{{ item.type }}"
    value: "{{ item.value }}"
   with_items:
    - {item: memlock, type: -, value: unlimited}

 - name: Download ES Package
   uri: 
    url: "{{ package_url }}"
    dest: "{{ tempdir }}/{{ fullname }}"
    creates: "{{ tempdir }}/{{ fullname }}"

 - block:
    - debug:
       msg: "Install ES"
    - unarchive:
       src: "{{ tempdir }}/{{ fullname }}" 
       dest: "{{ tempdir }}"
       owner: "{{ users.0.user }}"
       group: "{{ users.0.user }}"
       copy: no
       creates: "{{ tempdir }}/{{ name }}-{{ version }}"
    - synchronize:
       src: "{{ tempdir }}/{{ name }}-{{ version }}/"
       dest: "{{ basedir }}"
      delegate_to: "{{ inventory_hostname }}"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ basedir }}/{{ item }}"
      with_items:
       - "config/elasticsearch.yml"
       - "config/jvm.options"
    - file:
       path: "{{ item }}"
       owner: "{{ users.0.user }}"
       group: "{{ users.0.user }}"
       recurse: yes
       state: directory
      with_items: 
       - "{{ datadir }}"
       - "{{ backdir }}"

 - block:
    - debug:
       msg: "Setup ES Auto Start"
    - template:
       src: "{{ item }}.j2"
       dest: "/etc/systemd/system/{{ item }}"
      with_items:
       - "elasticsearch.service"
    - service:
       name: "elasticsearch"
       state: "restarted"
       enabled: yes

 - block:
    - debug:
       msg: "Install X-Pack"
    - shell: "{{ basedir }}/bin/elasticsearch-plugin install x-pack"
    - uri:
       url: "http://localhost:9200/_xpack/security/user/elastic/_password?pretty"
       user: "elastic"
       password: "changeme"
       method: "PUT"
       body_format: "json"
       body: "{ 'password': {{es.password}} }"
       force_basic_auth: yes
       
...
