---

 - name: Install Certbot From Yum
   yum:
     name: certbot
     state: present
   when: ansible_distribution_major_version == "7"

 - name: Install Certbot From Source
   get_url:
     url: https://dl.eff.org/certbot-auto
     dest: /usr/bin/certbot
     mode: 0755
   when: ansible_distribution_major_version == "6"

...
