---
 - name: Get torrent file
   copy:
     src: "/root/{{ distribute_name }}.torrent"
     dest: "/root/{{ distribute_name }}.torrent"

 - name: Start Peer 
   shell: SCREENRC=/dev/null SYSSCREENRC=/dev/null screen -dmS 'peerder' python {{ murder_install_dir }}/murder_client.py peer '/root/{{ distribute_name }}.torrent' '{{ distribute_path }}' {{ ansible_default_ipv4.address }} 
