 - name: Enable semi-sync replication on the master
   mysql_query:
    query: {{ items }}
   with_items:
      - "INSTALL PLUGIN rpl_semi_sync_master SONAME 'semisync_master.so'";
      - "INSTALL PLUGIN rpl_semi_sync_slave SONAME 'semisync_slave.so'";
      - "SET GLOBAL rpl_semi_sync_master_enabled=1;"
      - "SET GLOBAL rpl_semi_sync_master_timeout=2147483648;"
      - "SET GLOBAL rpl_semi_sync_slave_enabled=1;"

 - name: Check if semi-sync replication plugins are installed
   mysql_query:
    query: "SHOW PLUGINS LIKE '%semi%';"
    register: plugin_status

 - name: Debug the installed plugins
   debug:
    var: plugin_status

 - name: Create directory /usr/local/xenon
   file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
   with_items:
     - "/usr/local/xenon"

 - name: create file /usr/local/xenon/config.path
   copy:
    content: "/usr/local/xenon/xenon.conf.json"
    dest: /usr/local/xenon/config.path

 - name: copy xenon xenoncli to /usr/local/xenon
   copy:
    src: "{{ item }}"
    dest: /usr/local/xenon
    mode: '0755'
   with_items:
    - xenon
    - xenoncli

 - name: copy xenon.service to /etc/systemd/system
   copy:
    src: xenon.service
    dest: /etc/systemd/system

 - name: Ensure xenon is started and enabled
   service:
    name: xenon
    state: started
    enabled: yes
 
 - name: sleep 10s
   shell: sleep 10

 - name: Generate cluster IPs with ports for all hosts
   set_fact:
    xenon_cluster: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '(.*)', '\\1:' + (xenon_port | string)) | join(',') }}"

 - name: Print the generated xenon_cluster string 
   debug:
    msg: "Xenon cluster: {{ xenon_cluster }}"

 - name: Add cluster using xenoncli
   shell: "/usr/local/xenon/xenoncli cluster add {{ xenon_cluster }}"

   