---
 - name: Install Nginx
   yum:
    name: "{{ nginx_package_url }}"
    state: present
   when: "ansible_distribution == 'CentOS'"

 - name: Install Nginx on Ubuntu
   apt:
    deb: "{{ item }}"
   with_items:
     - "{{ Nginx_Package_for_ubuntu }}"
   when: "ansible_distribution == 'Ubuntu'"

 - name: Install depend on Ubuntu
   apt:
     name: ['zlib1g-dev', 'libgd-dev', 'libgeoip-dev']
     update_cache: yes
   when: "ansible_distribution == 'Ubuntu'"

 - name: Start Daemon When System Boot
   lineinfile:
    dest: /etc/rc.local
    create: yes
    line: "{{ nginx_install_dir }}/sbin/nginx"

 - name: Create Logs Dir
   file:
    path: "{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
    mode: 0755
    state: directory
   with_items:
     - "{{ nginx_logs_dir }}"
     - "{{ nginx_install_dir }}/logs"

 - name: Set Regular Clean Nginx Logs
   template: 
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx

 - name: crontab to logrotate log
   cron:
     name: nginx log to logrotate
     minute: "59"
     hour: "23"
     job: "sudo /usr/sbin/logrotate -f /etc/logrotate.d/nginx"
     user: "{{ ansible_ssh_user }}"

 - name: Set nginx.conf to nginx config dir
   copy:
     src: nginx.conf
     dest: "{{ nginx_install_dir }}/conf"

 - name: Copy common conf to nginx config dir
   copy:
     src: "common"
     dest: "{{ nginx_install_dir }}/conf"

 - name: Ceate vhost vssl dir
   file:
     path: "{{ nginx_install_dir }}/conf/{{ item }}"
     owner: root
     group: root
     recurse: yes
     state: directory
   with_items:
     - "vssl"
     - "vhost"

 - name: Set defualt ssl pem and key
   copy:
     src: "{{ item }}"
     dest: "{{ nginx_install_dir }}/conf/vssl"
   with_items:
     - "server.crt"
     - "server.key"


 - name: Set Environment PATH 
   lineinfile: 
    dest: "/etc/profile"
    line: "export PATH={{ nginx_install_dir }}/sbin:$PATH"

...
