---
 - name: Import secret yml
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Check if mysql-python has been installed
   shell: "rpm -qa|grep -i mysql-python"
   register: result
   ignore_errors: true
 
 - name: Install mysql-python
   yum:
     name: MySQL-python
     state: present
   when: result.rc != 0

 - name: Create a new database
   mysql_db:
     login_unix_socket: "{{ mysql_sock_dir }}"
     name: "{{ db_name }}"
     state: present


 - name: Grant privileges
   mysql_user:
     login_unix_socket: "{{ mysql_sock_dir }}"
     name: "{{ db_name }}"
     password: "{{ db_passwd }}"
     host: "{{ db_host }}"
     priv:  "{{ db_name }}.*:ALL"
     state: present
