---
 - name: Check If MySQL Conf Exists
   stat:
     path: "{{ mysql_conf_dir }}"
   register: result
   ignore_errors: true

 - name: Create MySQL Backup Dir
   file:
     path: "/data0/backups/{{ inventory_hostname }}/mysql_conf"
     state: directory
   delegate_to: localhost
   when: result.stat.exists

 - name: Backup MySQL Conf
   synchronize:
     src: "{{ mysql_conf_dir }}"
     dest: "/data0/backups/{{ inventory_hostname }}/mysql_conf"
     archive: yes
     mode: pull
   when: result.stat.exists
