---
 - name: Get node.js Package From Source
   get_url:
     url: "{{ node_package_url }}.tar.xz"
     dest: "{{ build_dir }}"

 - name: Unarchive Node
   unarchive:
     src: "{{ build_dir }}/node-{{ node_version }}-linux-x64.tar.xz"
     dest: "{{ node_install_dir }}"
     remote_src: yes

 - name: Rename Node Install Dir
   shell: "mv {{ node_install_dir }}/node-{{ node_version }}-linux-x64 {{ node_install_dir }}/node-{{ node_version }}"
   run_once: true   

 - name: Link Node
   file:
     src: "{{ node_install_dir }}/node-{{ node_version }}"
     path: "{{ node_link_dir }}"
     state: link
     force: yes

 - name: Add node Mirror Source
   template: src=npmrc.j2 dest=~/.npmrc

 - name: Export PATH
   lineinfile:
     dest: "/etc/profile"
     line: "export PATH={{ node_link_dir }}/bin:$PATH" 

 - name: Source Profile
   shell: "source /etc/profile"
...
