---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Set Shadowsocks-libev Yum Repo
   copy:
    src: "shadowsocks-libev.repo"
    dest: "/etc/yum.repos.d/shadowsocks-libev.repo"

 - name: Install Shadowsocks-libev
   yum:
    name: "shadowsocks-libev"
    state: present

 - name: Copy Config.json
   template:
    src: "{{ item }}.j2"
    dest: "/etc/shadowsocks-libev/{{ item }}"
   with_items:
    - "config.json"
    - "client.config.json"

 - name: Start Shadowsocks-libev
   service: 
    name: "shadowsocks-libev"
    state: restarted
    enabled: yes
   when: install_type == "server"

 - name: Copy Shadowsocks-client.service
   template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
   with_items:
    - "shadowsocks-client.service"

 - name: Start Shadowsocks-client
   service: 
    name: "shadowsocks-client"
    state: restarted
   when: install_type == "client"
