---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Add Basic Repo
   get_url: 
    url: http://mirrors.aliyun.com/repo/Centos-{{ ansible_distribution_major_version }}.repo 
    dest: /etc/yum.repos.d/CentOS-Base.repo 

 - name: Add Rpmforege And Epel Repo
   yum: 
    name: "{{ item }}" 
    state: present
    update_cache: yes
   with_items:
    - http://mirrors.aliyun.com/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - "{{ RPMFORGE }}"
 
...
