---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: install dependent packages
   apt_rpm:
    name: unixODBC 
    state: present
   when: "ansible_distribution == 'CentOS'"


 - name: install redis module
   pip:
     name: redis
     state: latest
     executable: pip

 - name: Install Zabbix-agentd On CentOS 7
   yum: 
    name: "{{ Zabbix_Agent_Package }}"
    state: present
   when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'"

 - name: Install Zabbix-agentd On CentOS 6
   yum: 
    name: "{{ Zabbix_Agent_Package }}"
    state: present
   when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'"

 #- name: Download Zabbix-agentd package on Ubuntu
 #  get_url:
 #   url: {{ Zabbix_Agent_Package_for_ubuntu }}
 #   dest: /tmp/zabbix-agent.deb
 #  when: "ansible_distribution == 'Ubuntu'

 - name: Install depend on Ubuntu
   apt:
    name: libcurl3
    update_cache: yes
   when: "ansible_distribution == 'Ubuntu'"

 - name: Install zabbix_agent package on Ubuntu from internet
   apt:
    deb: "{{ Zabbix_Agent_Package_for_ubuntu }}"
   when: "ansible_distribution == 'Ubuntu'"

 - name: Copy Zabbix_agent.conf
   template: 
    src: "zabbix_agentd.conf.{{ Mode }}.j2" 
    dest: "/etc/zabbix/zabbix_agentd.conf"

 - name: Delete Old Zabbix_agentd.d Directory
   file:
    path: "/etc/zabbix/zabbix_agentd.d"
    state: absent

 - name: Create Zabbix Monitor Logs Directory
   file:
    path: "/data/logs/zabbix_agent"
    owner: zabbix
    group: zabbix
    state: directory
    recurse: yes

 - name: Copy git key to remote
   copy:
     src: /data/var/key/git.key
     dest: /tmp/git.key
     mode: 0600

 - name: Checkout Zabbix_agentd.d
   git:
    repo: "{{ GIT_ADDR }}"
    dest: /etc/zabbix/zabbix_agentd.d
    accept_hostkey: yes
    key_file: /data/var/key/git.key
   notify:
    - Restart Zabbix-agentd

 - name: Delete git key
   file:
     path: "/tmp/git.key"
     state: absent
...
