---
 - name: Download phpredis package
   unarchive:
    src: "{{ phpredis_package_url }}"
    dest: "{{ tempdir }}"
    remote_src: True


 - name: make and make install phpredis
   shell: "{{ php_install_dir }}/bin/phpize && ./configure --with-php-config={{ php_install_dir }}/bin/php-config && make && make install"
   args:
     chdir: "/tmp/phpredis-{{ phpredis_version }}"

...
