---
 - hosts: cluster
   become: yes
   become_method: "{{ become_method }}"
   roles:
     - cluster


 - hosts: standalone
   become: yes
   become_method: "{{ become_method }}"
   roles:
     - standalone
