---
 - hosts: html
   roles:
     - nginx
     #- svncode

 - hosts: php
   roles:
     - nginx
     - php
     - svncode
     - mysql

 - hosts: php_git
   roles:
     - nginx
     - php
     - gitcode
