---
 - hosts: html
   roles:
     - nginx
     - svncode

 - hosts: php
   roles:
     - nginx
     - php
     - svncode

 - hosts: php_git
   roles:
     - nginx
     - php
     - gitcode

 - hosts: svn_hook
   roles:
     - svn_hook
