---

 - name: 获取当前最大mysql实例端口号,并加一作为新实例的端口号
   find:
    paths: "{{ mysql_datadir }}"
    patterns: '^\d{4}$'
    file_type: directory
    use_regex: yes
   register: pathglob

 - name: 设置实例默认端口号
   set_fact:
    port: 3307
   when: pathglob.files == []

 - name: 设置实例端口号
   set_fact:
    port: "{{ pathglob.files[-1].path|basename|int + 1|default(3307) }}"
   when: pathglob.files != []

 - name: 创建实例目录
   file:
    path: "{{ item }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_user }}"
    state: directory
    recurse: yes
   with_items:
    - "{{ mysql_datadir }}/{{ port }}/data"
    - "{{ mysql_datadir }}/{{ port }}/logs/binlog"
    - "{{ mysql_datadir }}/{{ port }}/logs/relaylog"
    
 - name: 复制配置文件以及管理脚本
   template:
    src: "{{ item.file }}.j2"
    dest: "{{ mysql_datadir }}/{{ port }}/{{ item.file }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_user }}"
    mode: "{{ item.mode }}"
   with_items:
    - { file: 'mysqld', mode: 700 }
    - { file: 'my.cnf', mode: 644 }

...
