---
url_prefix: 'http://download-miguan-com.oss-cn-hangzhou.aliyuncs.com/Packages/elk/kibana'

kibana: { host: '127.0.0.1', port: 5601, server_name: 'kibana.miguan.com' }
es: { host: '127.0.0.1', port: 9200, user: 'elastic', password: '2BntZyxIKGHMwXrj' }
