---
 - name: Check If Php Conf Exists
   stat:
     path: "{{ php_conf_dir }}"
   register: result
   ignore_errors: true

 - name: Create Php Backup Dir
   file:
     path: "/data0/backups/{{ inventory_hostname }}/php_conf"
     state: directory
   delegate_to: localhost
   when: result.stat.exists

 - name: Backup Php Conf
   synchronize:
     src: "{{ php_conf_dir }}"
     dest: "/data0/backups/{{ inventory_hostname }}/php_conf"
     archive: yes
     mode: pull
   when: result.stat.exists
