---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Dependent Packages
   yum:
    name: "{{ item }}"
    state: present
   with_items:
    - gcc
    - pcre-devel
    - zlib-devel
    - openssl-devel

 - name: Get Nginx Source Code
   uri:
    url: "{{ nginx_package_url }}"
    dest: "{{ build_dir }}"
    creates: "{{ build_dir }}/{{ nginx_package }}.tar.gz"

 - block: 
    - debug: 
       msg: Build Nginx Source Code
    - unarchive:
       src: "{{ build_dir }}/{{ nginx_package }}.tar.gz"
       dest: "{{ build_dir }}"
       copy: no
       creates: "{{ build_dir }}/{{ nginx_package }}"
    - shell: cd "{{ build_dir }}/{{ nginx_package }}" && ./configure  \
        "--user={{ nginx_user }}" \
        "--group={{ nginx_user }}" \
        "--prefix={{ nginx_install_dir }}" \
        --with-http_stub_status_module \
        --with-http_ssl_module \
        --with-http_sub_module \
        --with-md5=/usr/lib \
        --with-sha1=/usr/lib \
        --with-http_gzip_static_module \
        --with-http_stub_status_module \
        --with-http_realip_module \
        --with-debug
    - shell: cd "{{ build_dir }}/{{ nginx_package }}" && make && make install
 
 - block:
    - debug:
       msg: Get Nginx Conf
    - file: 
       path: "{{ nginx_install_dir }}/conf"
       state: absent
    - git: 
       repo: "{{ nginx_conf_url }}"
       dest: "{{ nginx_install_dir }}/conf"
       clone: yes
    - copy:
       src: default.htpasswd
       dest: "{{ nginx_install_dir }}/conf/setup/auth/htpasswd/"

 - name: Start Daemon When System Boot
   shell: echo "{{ nginx_install_dir }}/sbin/nginx" >> /etc/rc.local

 - name: Create Logs Dir
   file:
    path: "{{ nginx_logs_dir }}" 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    state: directory

 - name: Set Regular Clean Nginx Logs
   template: 
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx

 - name: Export PATH
   shell: echo "export PATH={{ nginx_install_dir }}/bin:\$PATH" >> /root/.bash_profile
...
