---
 - name: Modify /etc/ssh/sshd_config On CentOS 7
   copy: 
    src: sshd_config 
    dest: /etc/ssh/sshd_config
   when: ansible_distribution_major_version == '7'

 - name: Modify /etc/ssh/sshd_config On CentOS 6
   copy: 
    src: sshd_config 
    dest: /etc/ssh/sshd_config
   when: ansible_distribution_major_version == '6'

 - name: Add Authorized_keys
   authorized_key: 
    user: root 
    key: "{{ item }}" 
   with_file: 
    - public_keys/ops
...
