---
 - name: Modify /etc/ssh/sshd_config On CentOS 7/6
   copy: 
    src: sshd_config_{{ ansible_distribution_major_version }} 
    dest: /etc/ssh/sshd_config
   notify:
     - Restart sshd

 - name: Add Authorized_keys
   authorized_key: 
    user: root 
    key: "{{ item }}" 
   with_file: 
    - public_keys/ops
 - name: Add gitlab ssh-key
   copy:
    src: "id_rsa"
    dest: "~/.ssh/id_rsa"
    mode: "u=rw"
    owner: "root"
 ...
