---
 - name: Import secret yml
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Check Old Back Data
   find:
     paths: "{{ temp_dir }}"
     file_type: directory
     age: "1d"
     hidden: false
     recurse: no
     patterns: '2017*'
     use_regex: True
   register: old_data

 - name: Delete Old Backup Data
   file:
     path: "{{ item.path }}"
     state: absent
   with_items:
     - "{{ old_data.files }}"
   when: old_data.files != []

 - name: Check Old Back Data
   find:
     paths: "{{ temp_dir }}"
     file_type: directory
     hidden: false
     recurse: no
     patterns: '2017*'
     use_regex: True
   register: new_data

 - name: Recover Apply Log
   shell: "innobackupex --defaults-file={{ mysql_conf }} --apply-log  {{ item.path }} "
   with_items: 
     - "{{ new_data.files }}"
   when: new_data.files != []

 - name: Recover Copy Back
   shell: "innobackupex --defaults-file={{ mysql_conf }} --copy-back  {{ item.path }} "
   with_items:
     - "{{ new_data.files }}"
   when: new_data.files != []

 - name: Change Data Mode
   file: path={{ mysql_data_dir }}    owner={{ mysql_user }} group={{ mysql_user }} state=directory recurse=yes 

 - name: Start Mysql Instance
   command: "{{ mysql_bak_dir }}/mysqld start"

 - name: Get Master Binlog Info
   shell: "cat {{ item.path }}/xtrabackup_binlog_info"
   register: master_info
   with_items:
     - "{{ new_data.files }}"

 - debug:
     msg: "look  {{ master_info }}"

 - name: Init Slave
   mysql_replication:
     mode: resetslaveall
     login_unix_socket: "{{ mysql_sock }}"

 - name: Change Master To Slave
   mysql_replication:
     mode: changemaster
     login_unix_socket: "{{ mysql_sock }}"
     master_host: "{{ master_host }}"
     master_port: "{{ master_port }}"
     master_user: "{{ master_user }}"
     master_password: "{{ master_pass }}"
     master_log_file: "{{ item.stdout.split()[0] }}"
     master_log_pos: "{{ item.stdout.split()[1] }}"
     master_connect_retry: 50
     master_ssl: 0
   with_items:
     - "{{ master_info.results }}"

 - name: Start Slave
   mysql_replication:
     mode: startslave
     login_unix_socket: "{{ mysql_sock }}"
