---
- hosts: mysql_master
  become: yes
  tasks:
    - include_role:
        name: mysql
      vars:
        is_master: true

- hosts: mysql_slaves
  become: yes
  tasks:
    - include_role:
        name: mysql
      vars:
        is_slave: true

- hosts: all
  become: yes
  tasks:
    - name: Generate cluster IPs with ports for all hosts
      set_fact:
        xenon_cluster: "{{ groups['mysql_master'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '(.*)', '\\1:8801') | join(',') }},{{ groups['mysql_slaves'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '(.*)', '\\1:8801') | join(',') }}"
    
    - name: Print the generated xenon_cluster string
      debug:
        msg: "Xenon cluster: {{ xenon_cluster }}"