---
- name: Ensure MySQL is installed on Debian/Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server
    - mysql-client
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure MySQL is installed on CentOS/Rocky
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server
    - mysql
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes
