---
- name: stop slave
  mysql_replication:
    mode: stopreplica
  when: is_slave | default(false)

- name: change master on slaves
  mysql_replication:
    mode: changeprimary
    master_host: "{{ hostvars['master']['ansible_host'] }}"
    master_user: "{{ mysql_replication_user }}"
    master_password: "{{ mysql_replication_password }}"
    master_auto_position: true
  when: is_slave | default(false)

- name: start slave
  mysql_replication:
    mode: startreplica
  when: is_slave | default(false)
