 - name: Check if rpl_semi_sync_master is installed
   mysql_query:
    query: "SHOW PLUGINS;"
   register: plugin_status

 - name: Install semi-sync master plugin if not installed
   mysql_query:
    query: "INSTALL PLUGIN rpl_semi_sync_master SONAME 'semisync_master.so';"
   when: >
    not (plugin_status.query_result[0] | selectattr('Name', 'equalto', 'rpl_semi_sync_master') | list | length)

 - name: Install semi-sync slave plugin if not installed
   mysql_query:
    query: "INSTALL PLUGIN rpl_semi_sync_slave SONAME 'semisync_slave.so';"
   when: >
    not (plugin_status.query_result[0] | selectattr('Name', 'equalto', 'rpl_semi_sync_slave') | list | length)
 
 
 - name: Enable semi-sync replication on the master
   mysql_query:
    query: "{{ item }}"
   with_items:
      - "SET GLOBAL rpl_semi_sync_master_enabled=1;"
      - "SET GLOBAL rpl_semi_sync_master_timeout=2147483648;"
      - "SET GLOBAL rpl_semi_sync_slave_enabled=1;"

 - name: Create directory /usr/local/xenon
   file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
   with_items:
     - "/usr/local/xenon"

 - name: create file /usr/local/xenon/config.path
   copy:
    content: "/usr/local/xenon/xenon.conf.json"
    dest: /usr/local/xenon/config.path

 - name: copy xenon.conf.json to /usr/local/xenon
   template:
    src: xenon.conf.json.j2
    dest: /usr/local/xenon/xenon.conf.json
    mode: '0644'

 - name: copy xenon xenoncli to /usr/local/xenon
   copy:
    src: "{{ item }}"
    dest: /usr/local/xenon
    mode: '0755'
   with_items:
    - xenon
    - xenoncli

 - name: copy xenon.service to /etc/systemd/system
   copy:
    src: xenon.service
    dest: /etc/systemd/system

 - name: Ensure xenon is started and enabled
   service:
    name: xenon
    state: started
    enabled: yes
 
 - name: sleep 10s
   shell: sleep 10

 - name: Generate cluster IPs with ports for all hosts
   set_fact:
    xenon_cluster: "{{ all_host_ips | default([]) + [ansible_host] }}"

 - name: Print the generated xenon_cluster string 
   debug:
    msg: "Xenon cluster: {{ xenon_cluster }}"

 #- name: Add cluster using xenoncli
 #  shell: "/usr/local/xenon/xenoncli cluster add {{ xenon_cluster }}"

   