---
  - name: Check Nginx Start
    shell: "netstat -ntlp|grep 80"
    register: status

  - name: Start Nginx If Not Start   
    shell: "{{ nginx_basedir }}/sbin/nginx"
    when: status.rc != 0  

  - name: Copy Html Conf
    template:
     src: "html.conf.j2"
     dest: "{{ nginx_vhosts_dir }}/{{ nginx_server_name }}.conf"
    when: type == "html"
    notify:     
     - Reload Nginx

  - name: Copy The Php Conf
    template:
     src: "php.conf.j2"
     dest: "{{ nginx_vhosts_dir }}/{{ nginx_server_name }}.conf"
    when: type == "php"
    notify:     
     - Reload Nginx

  - name: Copy The Php Ssl  Conf
    template:
     src: "php_ssl.conf.j2"
     dest: "{{ nginx_vhosts_dir }}/{{ nginx_server_name }}.conf"
    when: type == "php_ssl"
    notify:     
     - Reload Nginx

  - name: Copy And Change The Proxy Conf
    template:
      src: "proxy.conf.j2"    
      dest: "{{ nginx_vhosts_dir }}/{{ nginx_server_name }}.conf"
    when: type == "proxy"
    notify:     
     - Reload Nginx
...
