---
#url_prefix: "https://artifacts.elastic.co/downloads/elasticsearch"

#elasticsearch install info
name: "elasticsearch"
version: "5.2.0"
suffix: "tar.gz"
fullname: "{{ name }}-{{ version }}.{{ suffix }}"
package_url: "{{ url_prefix }}/{{ fullname }}"
basedir: "/usr/local/webserver/{{ name }}"
tempdir: "/tmp"
datadir: ["/data0/elasticsearch/data0" ,"/data0/elasticsearch/data1"]
backdir: ["/data0/backups/elasticsearch"]
users: [{user: elasticsearch, id: 305, comment: "ES Server"}]
