---
# - name: Restart Zabbix-agentd On CentOS 7
#   shell: systemctl start zabbix-agent && systemctl enable zabbix-agent

 - name: Start usdtnode
   service: 
    name: usdtnode
    state: started
    enabled: yes

...
